### ISSUE TITLE
JWK validation fails if "use" is not present in key

### ISSUE THREAD

**Issue by cluetjen** [waldo2188/OpenIdConnectRelyingPartyBundle#1]
If the jwk returned from open id server contains no "use" property, signature validation fails with InvalidIdSignatureException.

Seems to be due to OICResponseHandler::verifySignedJwt():
  $key = $jwkSet->filterJwk("use", \JOSE_JWK::JWK_USE_SIG);

That's the JWKSet I had:

JOSE_JWKSet Object
(
    [keys] => Array
        (
            [0] => JOSE_JWK Object
                (
                    [components] => Array
                        (
                            [alg] => RS256
                            [e] => AQAB
                            [n] => 23zs5 ... 1pB-CP0
                            [kty] => RSA
                            [kid] => rsa1
                        )
                )
        )
)

As far as I understand, the "use" part is optional.

**Comment by waldo2188** [comment]
Hi,
You're right the "use" parameter is optional (http://self-issued.info/docs/draft-ietf-jose-json-web-key.html#useDef).

But for now, I have not yet planned the case where is not present.

I must handle this case. I will take a look at this point as soon as possible.

**Comment by waldo2188** [comment]
Hi!
I've made a fix for your issue, can you tell me if it's ok for you now?

**Comment by cluetjen** [comment]
Hi!
thanks for the quick update. In my project it's still not working. The problem seems to be, that filterJwk() returns an empty array if no key was found and so the $key === null condition will always be false.

JWKSet::filterJwk()
```php
    public function filterJwk($property, $value, $unique = false)
    {
        $out = array();
        foreach ($this->keys as $jwk) {

            if (array_key_exists($property, $jwk->components)) {
                if ($jwk->components[$property] == $value) {
                    $out[] = $jwk;
                }
            }
        }
        if (count($out) == 1 || $unique == true) {
            return $out[0];
        }
        return $out;
    }
```
OICResponseHandler::verifySignedJwt():185
```php
                $key = $jwkSet->filterJwk("use", \JOSE_JWK::JWK_USE_SIG);
                
                if ($key === null && array_key_exists(0, $jwkSet->keys) ) {
                	$key = $jwkSet->keys[0];
                }
            }
```
It works if I modify the condition to match empty arrays:
```php
                $key = $jwkSet->filterJwk("use", \JOSE_JWK::JWK_USE_SIG);
                
                if (($key === null || count($key) == 0) && array_key_exists(0, $jwkSet->keys) ) {
                	$key = $jwkSet->keys[0];
                }
```

**Comment by cluetjen** [comment]
Hi!
thanks for the quick update. Yes it works perfectly.
(I deleted my previous comment. The error described in this comment was due to an outdated version of gree/jose. Sorry for this.)

**Comment by waldo2188** [comment]
You're welcome ;)
