### ISSUE TITLE
[sf2.3] ServiceNotFoundException

### ISSUE THREAD

**Issue by rlavolee** [waldo2188/OpenIdConnectRelyingPartyBundle#2]
Hi,

Your bundle uses an non existent service in Symfony 2.3. The stack error looks like this:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                              
The service "waldo_oic_rp.logout" has a dependency on a non-existent service "security.token_storage".
```

It seems that "security.token_storage" service comes from the [Symfony 2.6 security improvements](http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements). I think the require symfony version should be update to `>= 2.6` in composer.json file.

**Comment by waldo2188** [comment]
My bad,
I've updated the composer.json to fix this issue
